name: MacOS Wheels Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            python: 311
            platform_id: macosx_x86_64

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11" # update once build dependencies are available

      - name: Build wheels
        run: bash {project}/scripts/build_macos.sh

